version: '3.8'

services:
  postgres:
    image: postgres:15.4
    hostname: postgres-service
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hland
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
  postgres-init:
    image: postgres:15.4
    restart: 'no'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PGPASSWORD=postgres
    entrypoint:
      - bash
      - -c
      - |
        echo Initializing default databases
        for i in {hobby_land};
         do psql -h postgres-service -U postgres -c "SELECT 1 FROM pg_database WHERE datname = '$$i'" | grep 0 && psql -h postgres-service -U postgres -c "CREATE DATABASE $$i";
        done
        echo Initialization complete
    networks:
      - hland
networks:
  hland:
volumes:
  postgres-data:
